### ISSUE TITLE
CancellationException

### ISSUE THREAD

**Issue by mondoktamas** [greensopinion/executor_lib#1]
Hello! 
I'm using the latest vector_map_tiles library with flutter_map, and i see some crashes on crashlytics with the following stacktrace

`Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Instance of 'CancellationException'. Error thrown null.`
       `at _IsolateExecutor.submit(isolate_executor.dart:72)`
      `at PoolExecutor.submit(pool_executor.dart:31)`
      `at TileProcessor.process(tile_processor.dart:17)`
      `at CachesTileProvider._createTiles.<fn>(caches_tile_provider.dart:73)`
      `at MapMixin.map(MapMixin.java)`
      `at CachesTileProvider._createTiles(caches_tile_provider.dart:71)`
      `at CachesTileProvider._provide(caches_tile_provider.dart:41)`
      `at _VectorTileModelLoader.startLoading(tile_model.dart:197)`
      

Unfortunately, i was not able to reproduce it.

**Comment by greensopinion** [comment]
Thanks for the issue. Looks like you're looking for this project: https://github.com/greensopinion/flutter-vector-map-tiles

CancellationException is a normal exception used by the library to indicate that a task has been cancelled. [vector_map_tiles](https://pub.dev/packages/vector_map_tiles) cancels jobs to process tiles when the tile is no longer needed (e.g. if the user is panning/zooming)

The reason you're seeing it in crashlytics is probably because the future has no associated handler. I tried to address this in [commit ab44c4011](https://github.com/greensopinion/flutter-vector-map-tiles/commit/ab44c4011fd93fc656f2a5a5226c4ba3d7dc8f33) but I must have missed at least one case. Feel free to submit a PR if you figure it out, otherwise these are safe to ignore.

**Comment by greensopinion** [comment]
Closed because this issue relates to `vector_map_tiles`, not this executor library
